//* All the movie to be loaded to the html movie-grids
export const movieCategories = [
    {
        category: "Popular Downloads",
        loadMore: "Browse More",
        movies: [
            {
                title: "Transformers One",
                year: 2024,
                img: "/img/movies/transformer-one-2024.jpg",
                rating: "8.5",
                genre: "Action<br/>Adventure",
            },
            {
                title: "Pashupati Prasad",
                year: 2016,
                img: "/img/movies/pasupati-prasad-2016.jpg",
                rating: "7.8",
                genre: "Comedy<br/>Drama",
            },
            {
                title: "Guras",
                year: 2023,
                img: "/img/movies/guras-2023.jpg",
                rating: "8.2",
                genre: "Drama",
            },
            {
                title: "Man From Kathmandu",
                year: 2019,
                img: "/img/movies/man-from-kathmandu-2019.jpg",
                rating: "7.5",
                genre: "Action<br/>Drama",
            },
        ],
    },

    {
        category: "Latest YIFY Movies Torrents",
        loadMore: "Browse All",
        movies: [
            {
                title: "12 Gaun",
                year: 2024,
                img: "/img/movies/12-Gaun-2024.jpg",
                rating: "7",
                genre: "Action",
            },
            {
                title: "Jatra",
                year: 2016,
                img: "/img/movies/jatra-2016.jpg",
                rating: "9",
                genre: "Comedy<br/>Drama",
            },
            {
                title: "Kalo Pothi",
                year: 2015,
                img: "/img/movies/kalo-pothi.jpg",
                rating: "9",
                genre: "Drama",
            },
            {
                title: "Bulbul",
                year: 2019,
                img: "/img/movies/bulbul-2019.jpg",
                rating: "8.8",
                genre: "Drama",
            },
            {
                title: "Inception",
                year: 2010,
                img: "/img/movies/inception-2010.jpg",
                rating: "8.8",
                genre: "Sci-Fi<br/>Thriller",
            },
            {
                title: "The Dark Knight",
                year: 2008,
                img: "/img/movies/dark-knight-2008.jpg",
                rating: "9.0",
                genre: "Action<br/>Thriller",
            },
            {
                title: "Parasite",
                year: 2019,
                img: "/img/movies/parasite-2019.jpg",
                rating: "8.6",
                genre: "Drama<br/>Thriller",
            },
            {
                title: "Forrest Gump",
                year: 1994,
                img: "/img/movies/forrest-gump-1994.jpg",
                rating: "8.8",
                genre: "Drama<br/>Romance",
            },
        ],
    },

    {
        category: "Upcoming YIFY Movies",
        loadMore: "Request a Movie",
        movies: [
            {
                title: "Transformers One",
                year: 2024,
                img: "/img/movies/transformer-one-2024.jpg",
                rating: "8.5",
                genre: "Action<br/>Adventure",
            },
            {
                title: "The Matrix",
                year: 1999,
                img: "/img/movies/matrix-1999.jpg",
                rating: "8.7",
                genre: "Sci-Fi<br/>Action",
            },
            {
                title: "Pashupati Prasad",
                year: 2016,
                img: "/img/movies/pasupati-prasad-2016.jpg",
                rating: "7.8",
                genre: "Comedy<br/>Drama",
            },
            {
                title: "Get Out",
                year: 2017,
                img: "/img/movies/get-out-2017.jpg",
                rating: "7.7",
                genre: "Horror<br/>Thriller",
            },
            {
                title: "Guras",
                year: 2023,
                img: "/img/movies/guras-2023.jpg",
                rating: "8.2",
                genre: "Drama",
            },
            {
                title: "Mad Max: Fury Road",
                year: 2015,
                img: "/img/movies/mad-max-fury-road-2015.jpg",
                rating: "8.1",
                genre: "Action<br/>Adventure",
            },
            {
                title: "Man From Kathmandu",
                year: 2019,
                img: "/img/movies/man-from-kathmandu-2019.jpg",
                rating: "7.5",
                genre: "Action<br/>Drama",
            },
            {
                title: "Fight Club",
                year: 1999,
                img: "/img/movies/fight-club-1999.jpg",
                rating: "8.8",
                genre: "Drama<br/>Thriller",
            },
        ],
    },
];
